rules:
  - id: custom-js-sql-injection-concat
    languages:
      - javascript
    severity: ERROR
    message: |
      🚨 VULNERABILIDADE CRÍTICA: SQL Injection detectada.
      Uma query SQL foi construída dinamicamente usando concatenação de strings,
      o que é uma prática perigosa. Utilize Prepared Statements ou ORMs
      para garantir a segurança.
    patterns:
      - pattern-either:
          - pattern: |
              $VAR = "... " + $INPUT
          - pattern: |
              $VAR = `... ${...} ...`
      - metavariable-regex:
          metavariable: $VAR
          regex: (?i)query|sql