name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Adicionar permissões corretas para o deploy
    permissions:
      contents: read
      pages: write
      id-token: write

    # Definir o ambiente de deploy para obter a URL correta
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Add execute permission to obfuscator
        run: chmod +x ./node_modules/.bin/javascript-obfuscator

      - name: Obfuscate code
        run: npm run obfuscate

      # Novo método de deploy
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Faz o upload do diretório raiz, que agora contém o código ofuscado
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 